services:
  valdaso:
    build: .
    container_name: val
    working_dir: /var/www/html/
    network_mode: "host"
    # ports:
    #   - '80:80'
    volumes:
      - type: bind
        source: .
        target: /var/www/html/
      # - ./moma-vue:/vue
      # - /home/vue/node_modules
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    # command: 'npm run serve'
    stdin_open: true
    tty: true
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
      # - CHOKIDAR_USEPOLLING=true
      # - CHOKIDAR_INTERVAL=1000
      - WDS_SOCKET_HOST=127.0.0.1 #for windows
      - CHOKIDAR_USEPOLLING=true #for windows
      - WATCHPACK_POLLING=true #for windows
    # command: "npm run dev"
    entrypoint: ["/bin/sh", "/var/www/html/entrypoint.sh"]
networks:
  host:
    external: true
